var xx2=-100
var def=125
var bbb1=-100
var bbb2=-100
var bbb3=-100
var bbbb1=186
var bbbb2=186
var bbbb3=186
var xP=240
var xN=-5
var cts123=0.35
var cts=cts123
var gameScreen=document.getElementById('screenGPB');var ctx=gameScreen.getContext('2d');var ctx2=gameScreen.getContext('2d');var cW=ctx.canvas.width,cH=ctx.canvas.height;var score=document.getElementById("score");var score2=document.getElementById("score2");var GG=document.getElementById("goodGuy");var BG=document.getElementById("badGuy");var EX=document.getElementById("explosion");var Pos=document.getElementById("position");var lifes=document.getElementById("life");var sped=document.getElementById("sped");var speed=parseFloat(sped.textContent);var BGX1=document.getElementById("random1")
var bgf1=document.getElementById("bgfall1");var BGX2=document.getElementById("random2")
var bgf2=document.getElementById("bgfall2");var BGX3=document.getElementById("random3")
var bgf3=document.getElementById("bgfall3");mySounds3=['Theme','Theme2','Theme3','Theme4','Theme5','Theme6','Theme7','Theme8']
var index3=Math.floor(Math.random()*1000)%mySounds3.length;var id3=mySounds3[index3];var audioElement3=document.getElementById(id3);mySounds2=['GameOver2','GameOver8']
var index2=Math.floor(Math.random()*1000)%mySounds2.length;var id2=mySounds2[index2];var audioElement2=document.getElementById(id2);let keyPresses={};var fallingbg1={};var looping={};var spedup={};var count={};var boxloop={};var startGame=false;var paused=false;var pauseM=false;var ded=false;var gradient=ctx2.createLinearGradient(0,0,gameScreen.width,0);gradient.addColorStop("0.05"," purple");gradient.addColorStop("0.5","orange");gradient.addColorStop("0.9","purple");ctx2.font='12px Comic Sans MS';ctx2.fillStyle=gradient;ctx2.fillText("LEFTARROW/A = LEFT   RIGHTARROW/D = RIGHT",2,64);ctx2.font='18px Comic Sans MS';ctx2.fillText("PRESS ANY BUTTON TO START",10,82);ctx2.fillText("MUSIC = M  PAUSE = P",48,100);ctx2.fillText("Hope You Enjoy!",85,118);window.addEventListener('keydown',function(startKeybButton){if(!startGame){togglePause(),togglePauseMusic(),startGame=true;};})
window.addEventListener('keyup',function(aka){if(aka.keyCode==80){togglePause();};})
window.addEventListener('keydown',function(pM){if(pM.keyCode==77){togglePauseMusic();};})
window.addEventListener("keydown",keyDownListener,false);function keyDownListener(event){event.repeat=true;keyPresses[event.key]=true;}
window.addEventListener("keyup",keyUpListener,false);function keyUpListener(event){keyPresses[event.key]=false;}
function loop(){var currentPos=parseFloat(Pos.textContent);if(keyPresses.ArrowLeft&&currentPos>xN){Pos.textContent=currentPos-speed;}else if(keyPresses.ArrowRight&&currentPos<xP){Pos.textContent=currentPos+speed;}else if(keyPresses.a&&currentPos>xN){Pos.textContent=currentPos-speed;}else if(keyPresses.d&&currentPos<xP){Pos.textContent=currentPos+speed;}};function speedup(bgsped,bgspeed){var bgsped=document.getElementById("bgsped");var bgspeed=parseFloat(bgsped.textContent);if(bgspeed<2){bgsped.textContent=bgspeed+0.1}};function fallbg1(){var lives=parseFloat(lifes.textContent);var livings=document.getElementById("livings");livings.innerHTML=parseFloat(lifes.textContent);var fall1=parseFloat(bgf1.textContent);var currentScore=parseFloat(score.textContent);var bgsped=document.getElementById("bgsped");var bgspeed=parseFloat(bgsped.textContent);if(fall1<150){bgf1.textContent=fall1+bgspeed;}else if(fall1=150&&currentScore>0){bgf1.innerHTML=Math.floor((Math.random()* -15)+ -60),score.textContent=currentScore-15,BGX1.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("passed").play();}else if(fall1=150&&currentScore<=0){lifes.textContent=lives-1,bgf1.innerHTML=Math.floor((Math.random()* -15)+ -60),BGX1.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("passed").play();}else if(fall1=150&&currentScore<=0&&lives>0){lifes.textContent=lives-1}
if(fall1>=-15&&fall1<=150){document.getElementById("fallingBadGuy").play(),document.getElementById("fallingBadGuy").volume=0.45;}else if(fall1<-15){document.getElementById("fallingBadGuy").pause(),document.getElementById("fallingBadGuy").currentTime=0;}
var lives=parseFloat(lifes.textContent);var livings=document.getElementById("livings");livings.innerHTML=parseFloat(lifes.textContent);var fall2=parseFloat(bgf2.textContent);var currentScore=parseFloat(score.textContent);var bgsped=document.getElementById("bgsped");var bgspeed=parseFloat(bgsped.textContent);if(fall2<150){bgf2.textContent=fall2+bgspeed;}else if(fall2=150&&currentScore>0){bgf2.innerHTML=Math.floor((Math.random()* -15)+ -30),score.textContent=currentScore-15,BGX2.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("passed").play();}else if(fall2=150&&currentScore<=0){lifes.textContent=lives-1,bgf2.innerHTML=Math.floor((Math.random()* -15)+ -60),BGX2.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("passed").play();}else if(fall2=150&&currentScore<=0&&lives>0){lifes.textContent=lives-1}
if(fall2>=-15&&fall2<=150){document.getElementById("fallingBadGuy2").play(),document.getElementById("fallingBadGuy2").volume=0.45;}else if(fall2<-15){document.getElementById("fallingBadGuy2").pause(),document.getElementById("fallingBadGuy2").currentTime=0;}
var lives=parseFloat(lifes.textContent);var livings=document.getElementById("livings");livings.innerHTML=parseFloat(lifes.textContent);var fall3=parseFloat(bgf3.textContent);var currentScore=parseFloat(score.textContent);var bgsped=document.getElementById("bgsped");var bgspeed=parseFloat(bgsped.textContent);if(fall3<150){bgf3.textContent=fall3+bgspeed;}else if(fall3=150&&currentScore>0){bgf3.innerHTML=Math.floor((Math.random()* -15)+ -30),score.textContent=currentScore-15,BGX3.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("passed").play();}else if(fall3=150&&currentScore<=0){lifes.textContent=lives-1,bgf3.innerHTML=Math.floor((Math.random()* -15)+ -60),BGX3.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("passed").play();}else if(fall3=150&&currentScore<=0&&lives>0){lifes.textContent=lives-1}
if(fall3>=-15&&fall3<=150){document.getElementById("fallingBadGuy3").play(),document.getElementById("fallingBadGuy3").volume=0.45;}else if(fall3<-15){document.getElementById("fallingBadGuy3").pause(),document.getElementById("fallingBadGuy3").currentTime=0;}};function alive(){var currentX=parseFloat(Pos.textContent);var lives=parseFloat(lifes.textContent);var livings=document.getElementById("livings");livings.innerHTML=parseFloat(lifes.textContent);score2.innerHTML=parseFloat(score.textContent)
ctx.fillStyle="#1f3328";ctx.fillRect(0,0,300,300);ctx.clearRect(0,0,300,300);if(lives>0){ctx.drawImage(GG,260,0,30,12),cLives.call();}else if(lives<1){death.call()}};function death(){ctx.fillStyle="#1f3328";ctx.fillRect(0,0,300,300);ctx.fillStyle="#1f3328";var gradient=ctx2.createLinearGradient(0,0,gameScreen.width,0);gradient.addColorStop("0.3"," purple");gradient.addColorStop("0.5","orange");gradient.addColorStop("0.7","purple");ctx2.fillStyle=gradient;ctx2.font='40px Comic Sans MS';ctx2.shadowOffsetX=3;ctx2.shadowOffsetY=3;ctx2.shadowColor="rgba(0,0,0,0.3)";ctx2.shadowBlur=4;ctx2.fillText("GAME",95,73);ctx2.fillText("OVER",100,103);audioElement3.pause();document.getElementById("fallingBadGuy").pause()
document.getElementById("fallingBadGuy2").pause()
document.getElementById("fallingBadGuy3").pause()
ded=true;audioElement2.play();audioElement2.loop=true;document.getElementById("GameOver2").volume=0.6;window.clearInterval(looping);window.clearInterval(fallingbg1);window.clearInterval(count);window.clearInterval(spedup);mySounds=['GameOver','GameOver3','GameOver4','GameOver5','GameOver6','GameOver7']
var index=Math.floor(Math.random()*1000)%mySounds.length;var id=mySounds[index];var audioElement=document.getElementById(id);audioElement.play();};function cLives(){var lives=parseFloat(lifes.textContent);var livings=document.getElementById("livings");livings.innerHTML=parseFloat(lifes.textContent);var currentScore=parseFloat(score.textContent);var currentX=parseFloat(Pos.textContent);var BGXPOS2=parseFloat(random1.textContent);var BGXPOS3=parseFloat(random2.textContent);var BGXPOS4=parseFloat(random3.textContent);var fall1=parseFloat(bgf1.textContent);var fall2=parseFloat(bgf2.textContent);var fall3=parseFloat(bgf3.textContent);var en1=[{"id":"enemy1","x1":BGXPOS2+8,"y1":fall1+2,"w1":50,"h1":15}]
var en2=[{"id":"enemy2","x2":BGXPOS3+8,"y2":fall2+2,"w2":50,"h2":15}]
var en3=[{"id":"enemy3","x3":BGXPOS4+8,"y3":fall3+2,"w3":50,"h3":15}];var gg1=[{"id":"GoodGuy1","x4":currentX+29,"y4":129,"w4":10,"h4":10}];var gg2=[{"id":"GoodGuy2","x5":currentX+5.9,"y5":133.5,"w5":56,"h5":10.5}];for(var i1=0;i1<en1.length;i1++){for(var i2=0;i2<en2.length;i2++){for(var i3=0;i3<en3.length;i3++){for(var i4=0;i4<gg1.length;i4++){for(var i5=0;i5<gg2.length;i5++){var e1=en1[i1];var e2=en2[i2];var e3=en3[i3];var g1=gg1[i4];var g2=gg2[i5];ctx.fillStyle="#1f3328";if(fall1>=100&&g1.x4+g1.w4>=e1.x1&&g1.x4<=e1.x1+e1.w1&&g1.y4>=e1.y1&&g1.y4<=e1.y1+e1.h1){bbb1=fall1,bbbb1=BGXPOS2,setTimeout(function(){bbb1=-100;},80);}else if(fall2>=100&&g1.x4+g1.w4>=e2.x2&&g1.x4<=e2.x2+e2.w2&&g1.y4>=e2.y2&&g1.y4<=e2.y2+e2.h2){bbb2=fall2,bbbb2=BGXPOS3,setTimeout(function(){bbb2=-100;},80);}else if(fall3>=100&&g1.x4+g1.w4>=e3.x3&&g1.x4<=e3.x3+e3.w3&&g1.y4>=e3.y3&&g1.y4<=e3.y3+e3.h3){bbb3=fall3,bbbb3=BGXPOS4,setTimeout(function(){bbb3=-100;},80);}else if(fall1>=100&&g2.x5+g2.w5>=e1.x1&&g2.x5<=e1.x1+e1.w1&&g2.y5>=e1.y1&&g2.y5<=e1.y1+e1.h1){bbb1=fall1,bbbb1=BGXPOS2,setTimeout(function(){bbb1=-100;},100),xx2=130,setTimeout(function(){xx2=-100;},200),setTimeout(function(){xx2=130;},300),setTimeout(function(){xx2=-100;},400),setTimeout(function(){xx2=130;},500),setTimeout(function(){xx2=-100;},600),def=180,setTimeout(function(){def=125;},700),ctx.fillRect(currentX,125,68,26.5),setTimeout(function(){def=180;},800),setTimeout(function(){def=125;},900),ctx.fillRect(currentX,125,68,26.5);}else if(fall2>=100&&g2.x5+g2.w5>=e2.x2&&g2.x5<=e2.x2+e2.w2&&g2.y5>=e2.y2&&g2.y5<=e2.y2+e2.h2){bbb2=fall2,bbbb2=BGXPOS3,setTimeout(function(){bbb2=-100;},100),xx2=130,setTimeout(function(){xx2=-100;},200),setTimeout(function(){xx2=130;},300),setTimeout(function(){xx2=-100;},400),setTimeout(function(){xx2=130;},500),setTimeout(function(){xx2=-100;},600),def=180,setTimeout(function(){def=125;},700),ctx.fillRect(currentX,125,68,26.5),setTimeout(function(){def=180;},800),setTimeout(function(){def=125;},900),ctx.fillRect(currentX,125,68,26.5);}else if(fall3>=100&&g2.x5+g2.w5>=e3.x3&&g2.x5<=e3.x3+e3.w3&&g2.y5>=e3.y3&&g2.y5<=e3.y3+e3.h3){bbb3=fall3,bbbb3=BGXPOS4,setTimeout(function(){bbb3=-100;},100),xx2=130,setTimeout(function(){xx2=-100;},200),setTimeout(function(){xx2=130;},300),setTimeout(function(){xx2=-100;},400),setTimeout(function(){xx2=130;},500),setTimeout(function(){xx2=-100;},600),def=180,setTimeout(function(){def=125;},700),ctx.fillRect(currentX,125,68,26.5),setTimeout(function(){def=180;},800),setTimeout(function(){def=125;},900),ctx.fillRect(currentX,125,68,26.5);}
if(g1.x4+g1.w4>=e1.x1&&g1.x4<=e1.x1+e1.w1&&g1.y4>=e1.y1&&g1.y4<=e1.y1+e1.h1){score.textContent=currentScore+20,bgf1.innerHTML=Math.floor((Math.random()* -15)+ -60),BGX1.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play();}else if(g1.x4+g1.w4>=e2.x2&&g1.x4<=e2.x2+e2.w2&&g1.y4>=e2.y2&&g1.y4<=e2.y2+e2.h2){score.textContent=currentScore+20,bgf2.innerHTML=Math.floor((Math.random()* -25)+ -80),BGX2.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play();}else if(g1.x4+g1.w4>=e3.x3&&g1.x4<=e3.x3+e3.w3&&g1.y4>=e3.y3&&g1.y4<=e3.y3+e3.h3){score.textContent=currentScore+20,bgf3.innerHTML=Math.floor((Math.random()* -35)+ -100),BGX3.innerHTML=Math.floor((Math.random()*xP)+xN),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play();}else if(g2.x5+g2.w5>=e1.x1&&g2.x5<=e1.x1+e1.w1&&g2.y5>=e1.y1&&g2.y5<=e1.y1+e1.h1){lifes.textContent=lives-1,bgf1.innerHTML=Math.floor((Math.random()* -15)+ -60),BGX1.innerHTML=Math.floor((Math.random()*xP)+xN),ctx.drawImage(EX,BGXPOS2,fall1,66,20),ctx.drawImage(EX,currentX,125,66,20),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play(),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play();}else if(g2.x5+g2.w5>=e2.x2&&g2.x5<=e2.x2+e2.w2&&g2.y5>=e2.y2&&g2.y5<=e2.y2+e2.h2){lifes.textContent=lives-1,bgf2.innerHTML=Math.floor((Math.random()* -25)+ -80),BGX2.innerHTML=Math.floor((Math.random()*xP)+xN),ctx.drawImage(EX,BGXPOS3,fall2,66,20),ctx.drawImage(EX,currentX,125,66,20),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play(),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play();}else if(g2.x5+g2.w5>=e3.x3&&g2.x5<=e3.x3+e3.w3&&g2.y5>=e3.y3&&g2.y5<=e3.y3+e3.h3){lifes.textContent=lives-1,bgf3.innerHTML=Math.floor((Math.random()* -35)+ -100),BGX3.innerHTML=Math.floor((Math.random()*xP)+xN),ctx.drawImage(EX,BGXPOS4,fall3,66,20),ctx.drawImage(EX,currentX,125,66,20),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play(),document.getElementById("Death").pause(),document.getElementById("Death").currentTime=0,document.getElementById("Death").play();}
draw.call()
ctx.drawImage(BG,BGXPOS2,fall1,66,20),ctx.drawImage(BG,BGXPOS3,fall2,66,20),ctx.drawImage(BG,BGXPOS4,fall3,66,20);function draw(){ctx.drawImage(GG,currentX,def,68,26.5);};ctx.drawImage(EX,bbbb1,bbb1,66,18);ctx.drawImage(EX,bbbb2,bbb2,66,18);ctx.drawImage(EX,bbbb3,bbb3,66,18);ctx.drawImage(EX,currentX,xx2,66,18)}}}}}};function togglePause(){var gradient=ctx2.createLinearGradient(0,0,gameScreen.width,0);gradient.addColorStop("0.25"," purple");gradient.addColorStop("0.5","orange");gradient.addColorStop("0.8","purple");if(!paused){paused=true,looping=window.setInterval(loop,24),spedup=window.setInterval(speedup,60000),fallingbg1=window.setInterval(fallbg1,24),count=window.setInterval(alive,1),ctx.fillStyle="#1f3328",ctx.fillRect(0,0,300,300);}else if(paused&&!ded){paused=false,ctx2.fillStyle=gradient,audioElement2.pause(),ctx2.font='40px Comic Sans MS',ctx2.fillText("PAUSED",76,82),document.getElementById("passed").pause(),document.getElementById("fallingBadGuy").pause(),document.getElementById("fallingBadGuy2").pause(),document.getElementById("fallingBadGuy3").pause(),window.clearInterval(looping),window.clearInterval(fallingbg1),window.clearInterval(count),window.clearInterval(spedup);}};function togglePauseMusic(){if(!pauseM&&!ded){pauseM=true,ctx.fillStyle="#1f3328",ctx.fillRect(0,0,50,10),audioElement3.play(),audioElement3.volume=0.35,audioElement3.loop=true;}else if(pauseM&&!ded){pauseM=false,ctx.clearRect(0,0,50,10),ctx2.fillStyle="#8f021a",ctx2.font='8px Impact',ctx2.fillText("MUSIC PAUSED",2,8),audioElement3.pause(),audioElement2.pause(),audioElement3.currentTime=0;}};